name: Run Apidog Tests Every Morning

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  apidog-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Apidog CLI
        run: npm install -g apidog-cli

      - name: Run API Tests
        run: apidog run --access-token $APIDOG_ACCESS_TOKEN -t 1108197 -e 3650510 -n 1 -r html,cli
