name: Automated API Tests

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Apidog CLI
        run: npm install -g apidog-cli

      - name: Run Test Scenario
        env:
          APIDOG_ACCESS_TOKEN: ${{ secrets.APIDOG_ACCESS_TOKEN }}
        run: |
          apidog run \
            --access-token $APIDOG_ACCESS_TOKEN \
            -t 1108197 \
            -e 3650510 \
            -n 1 \
            -r html,cli \
            --reporter-html-export ./report.html

      - name: Upload HTML Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: apidog-html-report
          path: ./report.html
